# Generated by Django 5.1.7 on 2025-03-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0002_remove_transaction_price_at_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
